# NumPy
***

## Introduction to NumPy

In [15]:
import numpy as np

x = np.random.uniform(0,1, size=2)

# Mean es promedio y lo esta haciendo con un array
x.mean()

0.5907058096455348

## NumPy Array

In [16]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [17]:
type(a)

numpy.ndarray

In [18]:
a = np.zeros(3)
type(a[0])

numpy.float64

In [19]:
a = np.zeros(3,dtype=int)
type(a[0])

numpy.int64

## Shape and Dimension

In [40]:
import numpy as np

z =np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
z.shape

(10,)

In [42]:
z.shape = (10,1)
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [46]:
z = np.zeros(4)
z.shape = (2, 2)
z


array([[0., 0.],
       [0., 0.]])

## Creating Arrays

In [48]:
z = np.empty(3)
z

array([0., 0., 0.])

In [53]:
z = np.linspace(1,39,9)
z

array([ 1. ,  8.6, 16.2, 23.8, 31.4, 39. ])

In [56]:
z = np.identity(2)
z

array([[1., 0.],
       [0., 1.]])

In [58]:
z = np.array([10,20])
z

array([10, 20])

In [60]:
type(z)

numpy.ndarray

In [62]:
z = np.array((10,20), dtype=float)
z

array([10., 20.])

In [63]:
z = np.array([[1,2],[3,4]])
z

array([[1, 2],
       [3, 4]])

In [66]:
na = np.linspace(10,20,2)
na is np.asarray(na)

True

In [67]:
na is np.array(na)

False

## Array Indexing

In [70]:
z = np.linspace(1,2,5)
z

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [71]:
z[0]

1.0

In [72]:
z[1:3]

array([1.25, 1.5 ])

In [73]:
z[-1]

2.0

In [74]:
z = np.array([[1,2],[3,4]])
z

array([[1, 2],
       [3, 4]])

In [75]:
z[0,0]

1

In [76]:
z[0,1]

2

Columns and rows can be extracted as follows

In [79]:
z[0, :]

array([1, 2])

In [78]:
z[:, 1]

array([2, 4])

In [80]:
z = np.linspace(2,4,5)
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [84]:
indices = np.array((0,2,3))
z
z[indices]

array([2. , 3. , 3.5])

In [87]:
d = np.array([0,1,1,1,0], dtype=bool)
d

array([False,  True,  True,  True, False])

In [88]:
z[d]

array([2.5, 3. , 3.5])

In [89]:
z = np.empty(3)
z

array([2.5, 3. , 3.5])

In [90]:
z[:] =42
z

array([42., 42., 42.])

## Array Methods

In [92]:
a = np.array((4,3,2,1))
a

array([4, 3, 2, 1])

In [93]:
a.sort()
a

array([1, 2, 3, 4])

In [94]:
a.sum()

10

In [95]:
a.mean()

2.5

In [96]:
a.max()

4

argmax() te da el index del elemento mayor

In [97]:
a.argmax()

3

In [98]:
a.cumsum() # Suma acumulativa de los elementos en un array

array([ 1,  3,  6, 10])

In [99]:
a.cumprod() # Multiplicacion acumulativa de los elementos en un array

array([ 1,  2,  6, 24])

In [100]:
a.var() #Varianza

1.25

In [101]:
a.std() # Desviacion estandar<

1.118033988749895

In [103]:
a.shape = (2,2) 
a.T # Equivalente a escribir a.transpose() osea transpuesta

array([[1, 3],
       [2, 4]])

In [106]:
z = np.linspace(2,4,5)
z

array([2. , 2.5, 3. , 3.5, 4. ])

z.searchsorted(a) retorna el index del primer elemento de z que $>= a$

In [107]:
z.searchsorted(2.2)

1

In [108]:
a = np.array((4,3,2,1))
np.sum(a)

10

In [109]:
np.mean(a)

2.5

## Operations on Array

In [110]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a + b

array([ 6,  8, 10, 12])

In [111]:
a * b

array([ 5, 12, 21, 32])

In [112]:
a + 10

array([11, 12, 13, 14])

In [113]:
a * 10

array([10, 20, 30, 40])

In [114]:
A = np.ones((2,2))
B = np.ones((2,2))
A + B

array([[2., 2.],
       [2., 2.]])

In [115]:
A + 10

array([[11., 11.],
       [11., 11.]])

In [117]:
A * B

array([[1., 1.],
       [1., 1.]])

## Matrix Multiplication
Usar @ sirve para multiplicar

In [119]:
A = np.array((1,2))
B = np.array((10,20))
A @ B

50

In [121]:
A = np.array(((1,2),(3,4)))
A

array([[1, 2],
       [3, 4]])

In [122]:
A @ (0,1)

array([2, 4])

## Mutability and Copying Arraya

In [123]:
a = np.array([42,44])
a

array([42, 44])

In [124]:
a[-1] = 0
a

array([42,  0])

In [127]:
a = np.random.randn(3)
a

array([-1.27007873,  0.2123541 , -0.07203318])

In [128]:
b = a
b[0] = 0.0
a

array([ 0.        ,  0.2123541 , -0.07203318])

In [130]:
id(a)

140143513806528

In [132]:
id(b) # A Y B SON LO MISMO!!!

140143513806528

In [133]:
a = np.random.randn(3)
a

array([-1.68684477,  1.14630495,  0.55983659])

In [134]:
b = np.copy(a)
b

array([-1.68684477,  1.14630495,  0.55983659])

In [135]:
b[:] = 1
b

array([1., 1., 1.])

In [136]:
a

array([-1.68684477,  1.14630495,  0.55983659])

## Additional Functionality

### Vectorized Functions